apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 3.6.1
      helm:
        releaseName: flaresolverr
        valueFiles:
          - $values/k8s/apps/media/flaresolverr/values.yaml
    - repoURL: git@github.com:rpmwin/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
