apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-2-monitor
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend-2
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
