name: CI

on:
  push:
    branches: [main]
    paths:
      - "apps/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend-1: ${{ steps.filter.outputs.backend-1 }}
      backend-2: ${{ steps.filter.outputs.backend-2 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend-1:
              - 'apps/backend-1/**'
            backend-2:
              - 'apps/backend-2/**'

  backend-1:
    name: Build & Push backend-1
    needs: changes
    if: needs.changes.outputs.backend-1 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_S }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend-1
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend-1
          file: ./apps/backend-1/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-1:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-1:${{ github.sha }}
          cache-from: type=gha,scope=backend-1
          cache-to: type=gha,scope=backend-1,mode=max

  backend-2:
    name: Build & Push backend-2
    needs: changes
    if: needs.changes.outputs.backend-2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_S }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend-2
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend-2
          file: ./apps/backend-2/dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-2:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/backend-2:${{ github.sha }}
          cache-from: type=gha,scope=backend-2
          cache-to: type=gha,scope=backend-2,mode=max
